image: docker:latest

services: 
  - docker:dind

stages:
  - test
  - build

lint_and_test:
 image: rust:1.44.0
 stage: test
 script:
   - rustup component add rustfmt-preview
   - cargo fmt --all -- --check
   - cargo test --all
 tags:
   - docker


builder:
  stage: build
  script:
    - apk update && apk add --no-cache curl git
    - docker login registry.gitlab.com --username $USERNAME --password $PASSWORD
    - export VERSION=$(git rev-parse --short HEAD)
    - docker build -t registry.gitlab.com/sanathana/lagoon:$VERSION
    - docker push registry.gitlab.com/sanathana/lagoon:$VERSION
  only:
    - master
  tags:
    - docker
  
